### ISSUE TITLE
Is this gem released to rubygems.org ?

### ISSUE THREAD

**Issue by thesubr00t** [basecamp/full_request_logger#2]
I have rubygems.org as a source in my Gemfile :
```ruby
source 'https://rubygems.org'
...
gem 'full_request_logger'
```

When trying to `bundle install` I got :

> Could not find gem 'full_request_logger' in any of the gem sources listed in your Gemfile.

**Comment by dhh** [comment]
It has not yet been released. I'll cut a first release now 👍

On Tue, Oct 8, 2019 at 10:37 AM GitHub <notifications@github.com> wrote:


“I have rubygems.org as a source in my Gemfile :

source 'https://rubygems.org'
...
gem 'full_request_logger'
When trying to bundle install I got :


“Could not find gem 'full_request_logger' in any of the gem sources listed in your Gemfile.””
